<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartmentRepository extends EntityRepository
{
}
